In [ ]:
import pandas as pd 

df = pd.read_csv('D://Data-Analytics-Portfolio/contractor-operations-analytics/data/raw/customer_support_tickets.csv')
df.shape

(8469, 17)

In [4]:
df.head(5)

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [5]:
df.columns.to_list()

['Ticket ID',
 'Customer Name',
 'Customer Email',
 'Customer Age',
 'Customer Gender',
 'Product Purchased',
 'Date of Purchase',
 'Ticket Type',
 'Ticket Subject',
 'Ticket Description',
 'Ticket Status',
 'Resolution',
 'Ticket Priority',
 'Ticket Channel',
 'First Response Time',
 'Time to Resolution',
 'Customer Satisfaction Rating']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   object
 2   Customer Email                8469 non-null   object
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   object
 5   Product Purchased             8469 non-null   object
 6   Date of Purchase              8469 non-null   object
 7   Ticket Type                   8469 non-null   object
 8   Ticket Subject                8469 non-null   object
 9   Ticket Description            8469 non-null   object
 10  Ticket Status                 8469 non-null   object
 11  Resolution                    2769 non-null   object
 12  Ticket Priority               8469 non-null   object
 13  Ticket Channel                8469 non-null   object
 14  First Response Time           5650 non-null   object
 15  Time to Resolution            2769 non-null   object
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), object(14)
memory usage: 1.1+ MB

In [10]:
df.sample(5)

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
4320,4321,James Contreras,phillip06@example.net,21,Other,Google Pixel,2021-12-26,Cancellation request,Software bug,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Low,Social media,2023-06-01 04:00:54,NaN,NaN
1031,1032,Jody Rodriguez,deborah92@example.com,67,Male,Xbox,2021-07-29,Cancellation request,Product recommendation,I'm having an issue with the {product_purchase...,Open,NaN,Critical,Social media,NaN,NaN,NaN
3477,3478,Jacob Tanner,ronaldsampson@example.org,34,Other,Nintendo Switch Pro Controller,2020-12-23,Refund request,Payment issue,There seems to be a hardware problem with my {...,Closed,Team born our manager nation.,Critical,Phone,2023-06-01 13:39:42,2023-06-01 11:13:42,5.0
6685,6686,Samuel Williams,drakejasmin@example.com,19,Male,Roomba Robot Vacuum,2020-06-30,Product inquiry,Hardware issue,I'm having an issue with the {product_purchase...,Closed,Pass animal Mr direction various century.,Critical,Email,2023-06-01 18:42:07,2023-06-01 06:04:07,5.0
286,287,Richard Salas,anthonycooper@example.org,25,Other,Nintendo Switch,2021-10-23,Technical issue,Cancellation request,I've noticed a software bug in the {product_pu...,Pending Customer Response,NaN,Critical,Phone,2023-06-01 09:38:19,NaN,NaN

In [11]:
df.isna().sum()

Ticket ID                          0
Customer Name                      0
Customer Email                     0
Customer Age                       0
Customer Gender                    0
Product Purchased                  0
Date of Purchase                   0
Ticket Type                        0
Ticket Subject                     0
Ticket Description                 0
Ticket Status                      0
Resolution                      5700
Ticket Priority                    0
Ticket Channel                     0
First Response Time             2819
Time to Resolution              5700
Customer Satisfaction Rating    5700
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["Ticket ID"].duplicated().sum()

np.int64(0)

In [14]:
df["Ticket Type"].value_counts(dropna=False)

Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

In [15]:
df["Ticket Priority"].value_counts(dropna=False)

Ticket Priority
Medium      2192
Critical    2129
High        2085
Low         2063
Name: count, dtype: int64

In [16]:
df["Ticket Status"].value_counts(dropna=False)

Ticket Status
Pending Customer Response    2881
Open                         2819
Closed                       2769
Name: count, dtype: int64

In [17]:
df["Ticket Channel"].value_counts(dropna=False)

Ticket Channel
Email           2143
Phone           2132
Social media    2121
Chat            2073
Name: count, dtype: int64

In [18]:
for col in df.columns:
    print(col)

Ticket ID
Customer Name
Customer Email
Customer Age
Customer Gender
Product Purchased
Date of Purchase
Ticket Type
Ticket Subject
Ticket Description
Ticket Status
Resolution
Ticket Priority
Ticket Channel
First Response Time
Time to Resolution
Customer Satisfaction Rating

In [19]:
tickets = df.copy()

columns_to_drop = ["Customer Name",
    "Customer Email",
    "Customer Age",
    "Customer Gender",
    "Date of Purchase",
    "Customer Satisfaction Rating"]

tickets = tickets.drop(columns=columns_to_drop)

In [20]:
tickets.columns.tolist()

['Ticket ID',
 'Product Purchased',
 'Ticket Type',
 'Ticket Subject',
 'Ticket Description',
 'Ticket Status',
 'Resolution',
 'Ticket Priority',
 'Ticket Channel',
 'First Response Time',
 'Time to Resolution']

In [22]:
tickets["Product Purchased"].value_counts().head(20)

Product Purchased
Canon EOS                         240
GoPro Hero                        228
Nest Thermostat                   225
Amazon Echo                       221
Philips Hue Lights                221
LG Smart TV                       219
Sony Xperia                       217
Roomba Robot Vacuum               216
Apple AirPods                     213
LG OLED                           213
iPhone                            212
Sony 4K HDR TV                    210
LG Washing Machine                208
Garmin Forerunner                 208
Canon DSLR Camera                 206
Nikon D                           204
Nintendo Switch Pro Controller    203
Google Pixel                      203
Fitbit Charge                     202
Sony PlayStation                  202
Name: count, dtype: int64

In [23]:
tickets["Ticket Type"].value_counts(dropna=False)

Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

In [24]:
tickets["Ticket Channel"].value_counts(dropna=False)

Ticket Channel
Email           2143
Phone           2132
Social media    2121
Chat            2073
Name: count, dtype: int64

In [25]:
tickets = tickets.drop(columns=["Product Purchased"])

In [26]:
tickets = tickets.drop(columns=["Ticket Type"])

In [27]:
tickets.columns.tolist()

['Ticket ID',
 'Ticket Subject',
 'Ticket Description',
 'Ticket Status',
 'Resolution',
 'Ticket Priority',
 'Ticket Channel',
 'First Response Time',
 'Time to Resolution']

In [29]:
tickets[
    ["Ticket ID", "First Response Time", "Time to Resolution"]
].head(10)

   Ticket ID  First Response Time   Time to Resolution
0          1  2023-06-01 12:15:36                  NaN
1          2  2023-06-01 16:45:38                  NaN
2          3  2023-06-01 11:14:38  2023-06-01 18:05:38
3          4  2023-06-01 07:29:40  2023-06-01 01:57:40
4          5  2023-06-01 00:12:42  2023-06-01 19:53:42
5          6                  NaN                  NaN
6          7                  NaN                  NaN
7          8                  NaN                  NaN
8          9  2023-06-01 10:32:47                  NaN
9         10  2023-06-01 09:25:48                  NaN

In [28]:
tickets[["First Response Time" , "Time to Resolution"]].dtypes

First Response Time    object
Time to Resolution     object
dtype: object

In [30]:
tickets[["First Response Time", "Time to Resolution"]].isna().sum()

First Response Time    2819
Time to Resolution     5700
dtype: int64

In [31]:
tickets[
    ["Ticket ID", "Ticket Status", "First Response Time", "Time to Resolution"]
].head(20)

,Ticket ID,Ticket Status,First Response Time,Time to Resolution
0,1,Pending Customer Response,2023-06-01 12:15:36,NaN
1,2,Pending Customer Response,2023-06-01 16:45:38,NaN
2,3,Closed,2023-06-01 11:14:38,2023-06-01 18:05:38
3,4,Closed,2023-06-01 07:29:40,2023-06-01 01:57:40
4,5,Closed,2023-06-01 00:12:42,2023-06-01 19:53:42
5,6,Open,NaN,NaN
6,7,Open,NaN,NaN
7,8,Open,NaN,NaN
8,9,Pending Customer Response,2023-06-01 10:32:47,NaN
9,10,Pending Customer Response,2023-06-01 09:25:48,NaN
10,11,Closed,2023-06-01 17:46:49,2023-05-31 23:51:49
11,12,Closed,2023-06-01 12:05:51,2023-06-01 09:27:51
12,13,Pending Customer Response,2023-06-01 19:03:53,NaN
13,14,Pending Customer Response,2023-06-01 20:34:54,NaN
14,15,Closed,2023-06-01 06:22:55,2023-05-31 23:08:55
15,16,Pending Customer Response,2023-06-01 15:09:57,NaN
16,17,Closed,2023-06-01 19:46:59,2023-06-01 15:58:59
17,18,Pending Customer Response,2023-06-01 21:05:01,NaN
18,19,Open,NaN,NaN
19,20,Closed,2023-06-01 00:46:04,2023-06-01 20:29:04

In [34]:
tickets.groupby("Ticket Status")[
    ["First Response Time", "Time to Resolution"]
].count()

                           First Response Time  Time to Resolution
Ticket Status
Closed                                    2769                2769
Open                                         0                   0
Pending Customer Response                 2881                   0